/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily:{
        'poppins':'"poppins",sans-serif',
        'krona':'"KronaOneRegular", sans-serif',
      },
      colors:{
        fondoimghome:'#FFE9D1',
        darkish:'#000000',
        bluenavish:'#14213D',
        //redish:'#FCA311',
        redish:'#E7AD04',
        grayish:'#E5E5E5',
        whitish:'#FFFFFF',
        bglogo:'#2eb387',
        //bglogo:'#04e7ad',        
        //bglogotext:'#84594b',
        //bglogotext:'#133956',
        bglogotext:'#04e7ad',
        canvasBG1:'#ACE1FE',
        canvasBG2:'#E3C1E3',
        canvasBG3:'#EFECCC',
        canvasBG4:'#FCC3A4',
        canvasBG5:'#ACE2BD',
        canvasBG6:'#99DDD9',
        canvasBG7:'#B0CFE8',
        canvasBG8:'#FBE699',
        canvasBG9:'#DBECA9',
        canvasBG1dark:'#9acae4',
        canvasBG2dark:'#ccadcc',
        canvasBG3dark:'#d7d4b7',
        canvasBG4dark:'#e2af93',
        canvasBG5dark:'#9acbaa',
        canvasBG6dark:'#89c6c3',
        canvasBG7dark:'#9ebad0',
        canvasBG8dark:'#e1cf89',
        canvasBG9dark:'#c5d498',
        canvas1Txt:'#31B6FD',
        canvas2Txt:'#B964BB',
        canvas3Txt:'#D7D17F',
        canvas4Txt:'#F96A1B',
        canvas5Txt:'#30B85B',
        canvas6Txt:'#00ACA0',
        canvas7Txt:'#3987C7',
        canvas8Txt:'#F5C201',
        canvas9Txt:'#A5D028',
        }
      },
    }, 
  variants:{
    extend:{},
  },  
  plugins: [require('@shrutibalasa/tailwind-grid-auto-fit')],
}
